/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service';
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy';
import { Route as LayoutRouteImport } from './routes/_layout';
import { Route as LayoutIndexRouteImport } from './routes/_layout/index';
import { Route as AssetsSplatRouteImport } from './routes/assets.$';
import { Route as ApiTitleGeneratorRouteImport } from './routes/api/title-generator';
import { Route as ApiPromptGeneratorRouteImport } from './routes/api/prompt-generator';
import { Route as ApiParametricChatRouteImport } from './routes/api/parametric-chat';
import { Route as ApiOutlineTracerRouteImport } from './routes/api/outline-tracer';
import { Route as ApiLocalDbRouteImport } from './routes/api/local-db';
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing-status';
import { Route as ApiBillingProductsRouteImport } from './routes/api/billing-products';
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing-checkout';
import { Route as LayoutSubscriptionRouteImport } from './routes/_layout/subscription';
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth';
import { Route as LayoutSplatRouteImport } from './routes/_layout/$';
import { Route as ApiLocalStorageSplatRouteImport } from './routes/api/local-storage.$';
import { Route as ApiJacksonPollockSplatRouteImport } from './routes/api/jackson-pollock/$';
import { Route as LayoutShareIdRouteImport } from './routes/_layout/share/$id';
import { Route as LayoutAuthSettingsRouteImport } from './routes/_layout/_auth/settings';
import { Route as LayoutAuthHistoryRouteImport } from './routes/_layout/_auth/history';
import { Route as LayoutAuthEditorIdRouteImport } from './routes/_layout/_auth/editor/$id';

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any);
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTitleGeneratorRoute = ApiTitleGeneratorRouteImport.update({
  id: '/api/title-generator',
  path: '/api/title-generator',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiPromptGeneratorRoute = ApiPromptGeneratorRouteImport.update({
  id: '/api/prompt-generator',
  path: '/api/prompt-generator',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiParametricChatRoute = ApiParametricChatRouteImport.update({
  id: '/api/parametric-chat',
  path: '/api/parametric-chat',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOutlineTracerRoute = ApiOutlineTracerRouteImport.update({
  id: '/api/outline-tracer',
  path: '/api/outline-tracer',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiLocalDbRoute = ApiLocalDbRouteImport.update({
  id: '/api/local-db',
  path: '/api/local-db',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing-status',
  path: '/api/billing-status',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBillingProductsRoute = ApiBillingProductsRouteImport.update({
  id: '/api/billing-products',
  path: '/api/billing-products',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing-checkout',
  path: '/api/billing-checkout',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutSubscriptionRoute = LayoutSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutSplatRoute = LayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LayoutRoute,
} as any);
const ApiLocalStorageSplatRoute = ApiLocalStorageSplatRouteImport.update({
  id: '/api/local-storage/$',
  path: '/api/local-storage/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiJacksonPollockSplatRoute = ApiJacksonPollockSplatRouteImport.update({
  id: '/api/jackson-pollock/$',
  path: '/api/jackson-pollock/$',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutShareIdRoute = LayoutShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutAuthSettingsRoute = LayoutAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutAuthHistoryRoute = LayoutAuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutAuthEditorIdRoute = LayoutAuthEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => LayoutAuthRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/$': typeof LayoutSplatRoute;
  '/subscription': typeof LayoutSubscriptionRoute;
  '/api/billing-checkout': typeof ApiBillingCheckoutRoute;
  '/api/billing-products': typeof ApiBillingProductsRoute;
  '/api/billing-status': typeof ApiBillingStatusRoute;
  '/api/local-db': typeof ApiLocalDbRoute;
  '/api/outline-tracer': typeof ApiOutlineTracerRoute;
  '/api/parametric-chat': typeof ApiParametricChatRoute;
  '/api/prompt-generator': typeof ApiPromptGeneratorRoute;
  '/api/title-generator': typeof ApiTitleGeneratorRoute;
  '/assets/$': typeof AssetsSplatRoute;
  '/history': typeof LayoutAuthHistoryRoute;
  '/settings': typeof LayoutAuthSettingsRoute;
  '/share/$id': typeof LayoutShareIdRoute;
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute;
  '/api/local-storage/$': typeof ApiLocalStorageSplatRoute;
  '/editor/$id': typeof LayoutAuthEditorIdRoute;
}
export interface FileRoutesByTo {
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/$': typeof LayoutSplatRoute;
  '/': typeof LayoutIndexRoute;
  '/subscription': typeof LayoutSubscriptionRoute;
  '/api/billing-checkout': typeof ApiBillingCheckoutRoute;
  '/api/billing-products': typeof ApiBillingProductsRoute;
  '/api/billing-status': typeof ApiBillingStatusRoute;
  '/api/local-db': typeof ApiLocalDbRoute;
  '/api/outline-tracer': typeof ApiOutlineTracerRoute;
  '/api/parametric-chat': typeof ApiParametricChatRoute;
  '/api/prompt-generator': typeof ApiPromptGeneratorRoute;
  '/api/title-generator': typeof ApiTitleGeneratorRoute;
  '/assets/$': typeof AssetsSplatRoute;
  '/history': typeof LayoutAuthHistoryRoute;
  '/settings': typeof LayoutAuthSettingsRoute;
  '/share/$id': typeof LayoutShareIdRoute;
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute;
  '/api/local-storage/$': typeof ApiLocalStorageSplatRoute;
  '/editor/$id': typeof LayoutAuthEditorIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_layout': typeof LayoutRouteWithChildren;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/_layout/$': typeof LayoutSplatRoute;
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren;
  '/_layout/subscription': typeof LayoutSubscriptionRoute;
  '/api/billing-checkout': typeof ApiBillingCheckoutRoute;
  '/api/billing-products': typeof ApiBillingProductsRoute;
  '/api/billing-status': typeof ApiBillingStatusRoute;
  '/api/local-db': typeof ApiLocalDbRoute;
  '/api/outline-tracer': typeof ApiOutlineTracerRoute;
  '/api/parametric-chat': typeof ApiParametricChatRoute;
  '/api/prompt-generator': typeof ApiPromptGeneratorRoute;
  '/api/title-generator': typeof ApiTitleGeneratorRoute;
  '/assets/$': typeof AssetsSplatRoute;
  '/_layout/': typeof LayoutIndexRoute;
  '/_layout/_auth/history': typeof LayoutAuthHistoryRoute;
  '/_layout/_auth/settings': typeof LayoutAuthSettingsRoute;
  '/_layout/share/$id': typeof LayoutShareIdRoute;
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute;
  '/api/local-storage/$': typeof ApiLocalStorageSplatRoute;
  '/_layout/_auth/editor/$id': typeof LayoutAuthEditorIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$'
    | '/subscription'
    | '/api/billing-checkout'
    | '/api/billing-products'
    | '/api/billing-status'
    | '/api/local-db'
    | '/api/outline-tracer'
    | '/api/parametric-chat'
    | '/api/prompt-generator'
    | '/api/title-generator'
    | '/assets/$'
    | '/history'
    | '/settings'
    | '/share/$id'
    | '/api/jackson-pollock/$'
    | '/api/local-storage/$'
    | '/editor/$id';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$'
    | '/'
    | '/subscription'
    | '/api/billing-checkout'
    | '/api/billing-products'
    | '/api/billing-status'
    | '/api/local-db'
    | '/api/outline-tracer'
    | '/api/parametric-chat'
    | '/api/prompt-generator'
    | '/api/title-generator'
    | '/assets/$'
    | '/history'
    | '/settings'
    | '/share/$id'
    | '/api/jackson-pollock/$'
    | '/api/local-storage/$'
    | '/editor/$id';
  id:
    | '__root__'
    | '/_layout'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/_layout/$'
    | '/_layout/_auth'
    | '/_layout/subscription'
    | '/api/billing-checkout'
    | '/api/billing-products'
    | '/api/billing-status'
    | '/api/local-db'
    | '/api/outline-tracer'
    | '/api/parametric-chat'
    | '/api/prompt-generator'
    | '/api/title-generator'
    | '/assets/$'
    | '/_layout/'
    | '/_layout/_auth/history'
    | '/_layout/_auth/settings'
    | '/_layout/share/$id'
    | '/api/jackson-pollock/$'
    | '/api/local-storage/$'
    | '/_layout/_auth/editor/$id';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  TermsOfServiceRoute: typeof TermsOfServiceRoute;
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute;
  ApiBillingProductsRoute: typeof ApiBillingProductsRoute;
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute;
  ApiLocalDbRoute: typeof ApiLocalDbRoute;
  ApiOutlineTracerRoute: typeof ApiOutlineTracerRoute;
  ApiParametricChatRoute: typeof ApiParametricChatRoute;
  ApiPromptGeneratorRoute: typeof ApiPromptGeneratorRoute;
  ApiTitleGeneratorRoute: typeof ApiTitleGeneratorRoute;
  AssetsSplatRoute: typeof AssetsSplatRoute;
  ApiJacksonPollockSplatRoute: typeof ApiJacksonPollockSplatRoute;
  ApiLocalStorageSplatRoute: typeof ApiLocalStorageSplatRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service';
      path: '/terms-of-service';
      fullPath: '/terms-of-service';
      preLoaderRoute: typeof TermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy-policy': {
      id: '/privacy-policy';
      path: '/privacy-policy';
      fullPath: '/privacy-policy';
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof LayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof LayoutIndexRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/assets/$': {
      id: '/assets/$';
      path: '/assets/$';
      fullPath: '/assets/$';
      preLoaderRoute: typeof AssetsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/title-generator': {
      id: '/api/title-generator';
      path: '/api/title-generator';
      fullPath: '/api/title-generator';
      preLoaderRoute: typeof ApiTitleGeneratorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/prompt-generator': {
      id: '/api/prompt-generator';
      path: '/api/prompt-generator';
      fullPath: '/api/prompt-generator';
      preLoaderRoute: typeof ApiPromptGeneratorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/parametric-chat': {
      id: '/api/parametric-chat';
      path: '/api/parametric-chat';
      fullPath: '/api/parametric-chat';
      preLoaderRoute: typeof ApiParametricChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/outline-tracer': {
      id: '/api/outline-tracer';
      path: '/api/outline-tracer';
      fullPath: '/api/outline-tracer';
      preLoaderRoute: typeof ApiOutlineTracerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/local-db': {
      id: '/api/local-db';
      path: '/api/local-db';
      fullPath: '/api/local-db';
      preLoaderRoute: typeof ApiLocalDbRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/billing-status': {
      id: '/api/billing-status';
      path: '/api/billing-status';
      fullPath: '/api/billing-status';
      preLoaderRoute: typeof ApiBillingStatusRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/billing-products': {
      id: '/api/billing-products';
      path: '/api/billing-products';
      fullPath: '/api/billing-products';
      preLoaderRoute: typeof ApiBillingProductsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/billing-checkout': {
      id: '/api/billing-checkout';
      path: '/api/billing-checkout';
      fullPath: '/api/billing-checkout';
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/subscription': {
      id: '/_layout/subscription';
      path: '/subscription';
      fullPath: '/subscription';
      preLoaderRoute: typeof LayoutSubscriptionRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/_layout/_auth': {
      id: '/_layout/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof LayoutAuthRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/_layout/$': {
      id: '/_layout/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof LayoutSplatRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/api/local-storage/$': {
      id: '/api/local-storage/$';
      path: '/api/local-storage/$';
      fullPath: '/api/local-storage/$';
      preLoaderRoute: typeof ApiLocalStorageSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/jackson-pollock/$': {
      id: '/api/jackson-pollock/$';
      path: '/api/jackson-pollock/$';
      fullPath: '/api/jackson-pollock/$';
      preLoaderRoute: typeof ApiJacksonPollockSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/share/$id': {
      id: '/_layout/share/$id';
      path: '/share/$id';
      fullPath: '/share/$id';
      preLoaderRoute: typeof LayoutShareIdRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/_layout/_auth/settings': {
      id: '/_layout/_auth/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof LayoutAuthSettingsRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/_auth/history': {
      id: '/_layout/_auth/history';
      path: '/history';
      fullPath: '/history';
      preLoaderRoute: typeof LayoutAuthHistoryRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/_auth/editor/$id': {
      id: '/_layout/_auth/editor/$id';
      path: '/editor/$id';
      fullPath: '/editor/$id';
      preLoaderRoute: typeof LayoutAuthEditorIdRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
  }
}

interface LayoutAuthRouteChildren {
  LayoutAuthHistoryRoute: typeof LayoutAuthHistoryRoute;
  LayoutAuthSettingsRoute: typeof LayoutAuthSettingsRoute;
  LayoutAuthEditorIdRoute: typeof LayoutAuthEditorIdRoute;
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthHistoryRoute: LayoutAuthHistoryRoute,
  LayoutAuthSettingsRoute: LayoutAuthSettingsRoute,
  LayoutAuthEditorIdRoute: LayoutAuthEditorIdRoute,
};

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
);

interface LayoutRouteChildren {
  LayoutSplatRoute: typeof LayoutSplatRoute;
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren;
  LayoutSubscriptionRoute: typeof LayoutSubscriptionRoute;
  LayoutIndexRoute: typeof LayoutIndexRoute;
  LayoutShareIdRoute: typeof LayoutShareIdRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSplatRoute: LayoutSplatRoute,
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutSubscriptionRoute: LayoutSubscriptionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutShareIdRoute: LayoutShareIdRoute,
};

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingProductsRoute: ApiBillingProductsRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiLocalDbRoute: ApiLocalDbRoute,
  ApiOutlineTracerRoute: ApiOutlineTracerRoute,
  ApiParametricChatRoute: ApiParametricChatRoute,
  ApiPromptGeneratorRoute: ApiPromptGeneratorRoute,
  ApiTitleGeneratorRoute: ApiTitleGeneratorRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  ApiJacksonPollockSplatRoute: ApiJacksonPollockSplatRoute,
  ApiLocalStorageSplatRoute: ApiLocalStorageSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
